### ISSUE TITLE
Last touches of smart contracts before betanet

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/payments-smart-contracts#114]
- [x] Add uniswap support in topup
- [x] Add `settleIntoDEX` in provider channels
- [x] Better events in hermes channels
- [x] Versioning of Hermes channels #94 
- [ ] Debug hermes penalty math #44 
- [x] Hermes takes registration fee (?)
- [x] Fast withdrawal from consumer channels (when Hermes agrees)
- [x] Fixes after code review
- [x] Allow payment channels to upgrade MYST #115
